set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"

# prefixキーをC-tに変更する
set -g prefix C-t
unbind C-b

# 設定ファイルのリロード
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# ペインの分割
bind | split-window -h
bind - split-window -v

# Vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# ペインボーダーの色を設定する
set -g pane-border-fg green
set -g pane-border-bg black
# アクティブなペインを目立たせる
set -g pane-active-border-fg white
set -g pane-active-border-bg yellow

# ステータスバーを設定する
## リフレッシュの間隔を設定する(デフォルト 15秒)
set -g status-interval 60
## ステータスバーを上部に表示する
set -g status-position to
#set -g status-right '#[fg=black,bg=yellow,bold] [%Y-%m-%d(%a) %H:%M]#[default]'
set -g status-right '#[fg=black] [%Y-%m-%d(%a) %H:%M]#[default]'

# スクロールを有効にする
#set-option -g mouse on
#bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# コピーモード
set -s escape-time 0
set-window-option -g mode-keys vi
## Prefix+v でコピーモード開始
bind-key v copy-mode \; display "Copy mode!"
#bind-key -t vi-copy v begin-selection
## Prefix+Enter/y でコピー
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
bind-key -t vi-copy y     copy-pipe "reattach-to-user-namespace pbcopy"
## Prefix+p でペースト
bind-key p paste-buffer

# スクロール
#set -g mouse on
#set -g terminal-overrides 'xterm*:smcup@:rmcup@'
